/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AnalysisResult: ClassViewer<'AnalysisResult', "output" | "confidence" | "metadata">;
    
    CounterRitual: ClassViewer<'CounterRitual', "catalytic_option" | "safety_rail" | "ritual_hook" | "reflexive_note" | "collateral_risk" | "follow_up_trigger">;
    
    NarrativeProbe: ClassViewer<'NarrativeProbe', "foreground" | "chroma" | "multiplicity" | "viral_load" | "maven_mode" | "analysis">;
    
    SerologicScan: ClassViewer<'SerologicScan', "macro_name" | "host_identity" | "incentive_surface" | "replication_channel" | "beneficiaries" | "weak_link" | "viral_load">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AnalysisResult","CounterRitual","NarrativeProbe","SerologicScan",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AnalysisResult = this.tb.classViewer("AnalysisResult", [
          "output","confidence","metadata",
        ]);
        
        this.CounterRitual = this.tb.classViewer("CounterRitual", [
          "catalytic_option","safety_rail","ritual_hook","reflexive_note","collateral_risk","follow_up_trigger",
        ]);
        
        this.NarrativeProbe = this.tb.classViewer("NarrativeProbe", [
          "foreground","chroma","multiplicity","viral_load","maven_mode","analysis",
        ]);
        
        this.SerologicScan = this.tb.classViewer("SerologicScan", [
          "macro_name","host_identity","incentive_surface","replication_channel","beneficiaries","weak_link","viral_load",
        ]);
        
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}