/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AlternativeApproaches,  AnalysisResult,  Approach,  CounterRitual,  CriticalReview,  DeepAnalysis,  NarrativeProbe,  SerologicScan,  SynthesisResult,  ThoughtResponse } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AlternativeApproaches {
      approaches: Approach[]
      comparison_matrix?: string | null
      recommendation?: string | null
    }
    export interface AnalysisResult {
      output?: string | null
      confidence?: number | null
      metadata?: string | null
    }
    export interface Approach {
      name?: string | null
      mechanism?: string | null
      strengths: string[]
      weaknesses: string[]
      best_for?: string | null
      implementation_sketch?: string | null
    }
    export interface CounterRitual {
      catalytic_option?: string | null
      safety_rail?: string | null
      ritual_hook?: string | null
      reflexive_note?: string | null
      collateral_risk?: number | null
      follow_up_trigger?: string | null
    }
    export interface CriticalReview {
      overall_assessment?: string | null
      strengths: string[]
      vulnerabilities: string[]
      missing_considerations: string[]
      edge_cases: string[]
      specific_suggestions: string[]
      risk_level?: string | null
    }
    export interface DeepAnalysis {
      summary?: string | null
      technical_perspective?: string | null
      conceptual_perspective?: string | null
      practical_perspective?: string | null
      edge_cases: string[]
      connections: string[]
      recommendations: string[]
      uncertainties: string[]
    }
    export interface NarrativeProbe {
      foreground?: string | null
      chroma?: string | null
      multiplicity: string[]
      viral_load?: number | null
      maven_mode?: string | null
      analysis?: string | null
    }
    export interface SerologicScan {
      macro_name?: string | null
      host_identity?: string | null
      incentive_surface?: string | null
      replication_channel?: string | null
      beneficiaries: string[]
      weak_link?: string | null
      viral_load?: number | null
    }
    export interface SynthesisResult {
      executive_summary?: string | null
      key_themes: string[]
      points_of_agreement: string[]
      points_of_disagreement: string[]
      information_gaps: string[]
      actionable_insights: string[]
      decision_recommendation?: string | null
    }
    export interface ThoughtResponse {
      mode?: string | null
      key_questions: string[]
      challenges: string[]
      alternative_framings: string[]
      next_steps: string[]
      conversational_response?: string | null
    }
}