/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface AlternativeApproaches {
  approaches: Approach[]
  comparison_matrix: string
  recommendation: string
  
}

export interface AnalysisResult {
  output: string
  confidence: number
  metadata: string
  
}

export interface Approach {
  name: string
  mechanism: string
  strengths: string[]
  weaknesses: string[]
  best_for: string
  implementation_sketch: string
  
}

export interface CounterRitual {
  catalytic_option: string
  safety_rail: string
  ritual_hook: string
  reflexive_note: string
  collateral_risk: number
  follow_up_trigger: string
  
}

export interface CriticalReview {
  overall_assessment: string
  strengths: string[]
  vulnerabilities: string[]
  missing_considerations: string[]
  edge_cases: string[]
  specific_suggestions: string[]
  risk_level: string
  
}

export interface DeepAnalysis {
  summary: string
  technical_perspective: string
  conceptual_perspective: string
  practical_perspective: string
  edge_cases: string[]
  connections: string[]
  recommendations: string[]
  uncertainties: string[]
  
}

export interface NarrativeProbe {
  foreground: string
  chroma: string
  multiplicity: string[]
  viral_load: number
  maven_mode: string
  analysis: string
  
}

export interface SerologicScan {
  macro_name: string
  host_identity: string
  incentive_surface: string
  replication_channel: string
  beneficiaries: string[]
  weak_link: string
  viral_load: number
  
}

export interface SynthesisResult {
  executive_summary: string
  key_themes: string[]
  points_of_agreement: string[]
  points_of_disagreement: string[]
  information_gaps: string[]
  actionable_insights: string[]
  decision_recommendation: string
  
}

export interface ThoughtResponse {
  mode: string
  key_questions: string[]
  challenges: string[]
  alternative_framings: string[]
  next_steps: string[]
  conversational_response: string
  
}
